# Add application configuration variables here, as shown below.
#
# PUSHER_APP_ID: "2954"
# PUSHER_KEY: 7381a978f7dd7f9a1117
# PUSHER_SECRET: abdc3b896a0ffb85d373
# STRIPE_API_KEY: EdAvEPVEC3LuaTg5Q3z6WbDVqZlcBQ8Z
# STRIPE_PUBLIC_KEY: pk_BRgD57O8fHja9HxduJUszhef6jCyS

development:
  STRIPE_PUBLISHABLE_KEY: pk_test_pGUVCskWI3tiVY8Qqe0wgJpB
  STRIPE_SECRET_KEY: sk_test_qFwxOxnTSxsQmFrk3UUipiBf

test:
  STRIPE_PUBLISHABLE_KEY: pk_test_pGUVCskWI3tiVY8Qqe0wgJpB
  STRIPE_SECRET_KEY: sk_test_qFwxOxnTSxsQmFrk3UUipiBf\

production:
  STRIPE_PUBLISHABLE_KEY: pk_live_KBeryRczsoihNFCmcTIhoYvt
  STRIPE_SECRET_KEY: sk_live_CMujYh2NTHMmDp0NqAL8eKDO
